// Українська локалізація Repact. Внутрішній код мови — `ua`, формат дат — `uk-UA`.
window.UA_TRANSLATIONS = {
  "Choose language": "Оберіть мову",
  "Home": "Головна", "Challenges": "Челенджі", "Progress": "Прогрес", "Profile": "Профіль",
  "Active": "Активні", "Pending": "Очікують", "Browse": "Огляд", "Completed": "Завершені",
  "Today": "Сьогодні", "Today in Repact": "Сьогодні в Repact", "All-time": "За весь час",
  "All-time reps": "Повторів за весь час", "Earlier reps": "Попередні повтори", "Total reps": "Усього повторів",
  "Statistics": "Статистика", "Stats": "Статистика", "Daily activity — 30 days": "Денна активність за 30 днів",
  "Challenge": "Челендж", "Challenge complete!": "Челендж завершено!", "Challenge failed": "Челендж провалено",
  "Create challenge": "Створити челендж", "Create Challenge": "Створити челендж", "New challenge": "Новий челендж",
  "Find a challenge": "Знайти челендж", "Start challenge": "Почати челендж", "Public challenge": "Публічний челендж",
  "Private challenge": "Приватний челендж", "Review challenge": "Перевірте челендж", "Challenge type": "Тип челенджу",
  "Active challenges: %lld": "Активних челенджів: %lld", "Challenges joined": "Участь у челенджах",
  "No active challenges": "Немає активних челенджів", "No public challenges yet": "Публічних челенджів поки немає",
  "Public challenges you can join show up here.": "Тут з’являться публічні челенджі, до яких можна приєднатися.",
  "No finished challenges yet": "Завершених челенджів поки немає", "Completed challenges will show up here.": "Тут з’являться завершені челенджі.",
  "Nothing pending": "Нічого не очікує", "Create a new challenge to get started!": "Створіть челендж, щоб почати!",
  "Continue workout": "Продовжити тренування", "Start today's workout": "Почати тренування на сьогодні",
  "Finish workout": "Завершити тренування", "Finish workout?": "Завершити тренування?", "Save workout": "Зберегти тренування",
  "Workout saved": "Тренування збережено", "Workout sounds": "Звуки тренування", "Finish set": "Завершити підхід",
  "Start next set": "Почати наступний підхід", "Extra set": "Ще один підхід", "Rest": "Відпочинок",
  "Rest finished": "Відпочинок завершено", "Overall time": "Загальний час", "Day complete": "День завершено",
  "Day done!": "День завершено!", "Done": "Готово", "Done today": "Виконано сьогодні",
  "Done today: %lld/%lld": "Сьогодні: %lld/%lld", "Daily goal": "Денна ціль", "Goal reached!": "Цілі досягнуто!",
  "Push-ups": "Віджимання", "Squats": "Присідання", "Pull-ups": "Підтягування", "Dips": "Віджимання на брусах",
  "Push-ups per day": "Віджимань на день", "Squats per day": "Присідань на день", "Reps": "Повтори",
  "Reps per day": "Повторів на день", "reps per day": "повторів на день", "%lld reps": "%lld повторів",
  "%lld reps/day": "%lld повторів на день", "%lld / day": "%lld / день", "%lld days": "%lld днів",
  "%lld sets": "%lld підходів", "Sets": "Підходи", "Best set": "Найкращий підхід", "Average set": "Середній підхід",
  "Max reps": "Максимум за підхід", "Max reps in one set": "Максимум за підхід", "Time": "Час",
  "Try a demo workout": "Спробувати демо-тренування", "AI Workout": "AI-тренування", "Try 5 reps": "Спробувати 5 повторів",
  "Get started": "Почати", "Let's go": "Уперед", "Continue": "Далі", "Back": "Назад", "Close": "Закрити",
  "Create": "Створити", "Save": "Зберегти", "Cancel": "Скасувати", "Finish": "Завершити", "Retry": "Спробувати ще",
  "Camera setup": "Налаштування камери", "Open camera": "Відкрити камеру", "Switch camera": "Змінити камеру",
  "Camera tracking": "Відстеження камерою", "Point the camera at yourself": "Наведіть камеру на себе",
  "Set your phone down": "Надійно встановіть телефон", "Fit your whole body in frame": "Розмістіть усе тіло в кадрі",
  "Use good lighting": "Додайте світла", "Step into frame": "Станьте в кадр", "Step back from the camera": "Відійдіть далі від камери",
  "Show both arms": "Покажіть обидві руки", "Show both legs": "Покажіть обидві ноги", "Position found": "Позицію знайдено",
  "Too dark — add more light": "Надто темно — додайте світла", "Body found — hold still": "Тіло знайдено — не рухайтесь",
  "Ready — start moving": "Готово — починайте рух", "Reconnecting camera…": "Перепідключаємо камеру…",
  "Lower your chest": "Опустіть груди нижче", "Squat lower": "Присядьте нижче", "Pull yourself higher": "Підтягніться вище",
  "Lower your body": "Опустіться нижче", "Go a little deeper": "Ще трохи нижче", "Go!": "Уперед!",
  "Camera check complete": "Перевірку камери завершено", "Try again": "Спробувати ще раз", "Not now": "Не зараз",
  "Camera permission denied": "Доступ до камери заборонено", "Camera not found": "Камеру не знайдено",
  "Internet connection required": "Потрібне підключення до інтернету", "Open Settings": "Відкрити налаштування",
  "Before": "До", "After": "Після", "Before / After": "До / Після", "Before / After photos": "Фото до / після",
  "Take a photo": "Зробити фото", "Take photo": "Зняти фото", "Upload": "Завантажити", "Upload from library": "Завантажити з галереї",
  "Photo library": "Фотогалерея", "Retake": "Перезняти", "Show photos": "Показати фото",
  "Share": "Поділитися", "Share result": "Поділитися результатом", "Share your day": "Поділитися днем",
  "Share story": "Поділитися сторіс", "Share today's result": "Поділитися результатом", "Save to profile": "Зберегти в профіль",
  "Choose a background": "Оберіть фон", "Template": "Шаблон", "Minimal": "Мінімал", "Repact gradient": "Градієнт Repact",
  "Rules": "Правила", "Conditions": "Умови", "Duration": "Тривалість", "Duration (days)": "Тривалість (днів)",
  "Exercise": "Вправа", "Which exercises?": "Які вправи?", "How many per day?": "Скільки на день?",
  "Daily goal for each exercise.": "Денна ціль для кожної вправи.", "Pick at least one exercise": "Оберіть хоча б одну вправу",
  "Name your challenge": "Назвіть челендж", "Challenge name": "Назва челенджу", "Title": "Назва",
  "Buy-in": "Внесок", "Stake amount": "Розмір ставки", "Prize pool": "Призовий фонд", "Balance": "Баланс",
  "Test coins · no cash value": "Тестові монети · без грошової вартості", "Test currency — no real money.": "Тестова валюта — без реальних грошей.",
  "Leaderboard": "Таблиця лідерів", "Members: %lld": "Учасників: %lld", "Eliminated: %lld": "Вибуло: %lld",
  "Join for": "Приєднатися за", "Leave challenge": "Вийти з челенджу", "Leave challenge?": "Вийти з челенджу?",
  "Leave": "Вийти", "Keep going": "Продовжити", "Invite friends": "Запросити друзів", "Link copied": "Посилання скопійовано",
  "Your name": "Ваше ім’я", "Age": "Вік", "Gender": "Стать", "Male": "Чоловіча", "Female": "Жіноча",
  "Height": "Зріст", "Weight": "Вага", "Fitness level": "Рівень підготовки", "Beginner": "Початківець",
  "Athlete": "Атлет", "Measurements": "Заміри", "New measurement": "Новий замір", "kg": "кг", "cm": "см",
  "Account": "Акаунт", "Email": "Електронна пошта", "Password": "Пароль", "Log in": "Увійти", "Log out": "Вийти",
  "Sign up": "Зареєструватися", "Create account": "Створити акаунт", "Create your account": "Створіть акаунт",
  "Continue with Google": "Продовжити з Google", "Continue as guest": "Продовжити як гість", "Guest": "Гість", "or": "або",
  "Notifications": "Сповіщення", "No notifications yet": "Сповіщень поки немає", "Report a problem": "Повідомити про проблему",
  "Details (optional)": "Деталі (необов’язково)", "Send report": "Надіслати", "Thanks! Report sent.": "Дякуємо! Звіт надіслано.",
  "Counting & camera": "Підрахунок і камера", "Design & layout": "Дизайн і верстка", "App behavior": "Робота застосунку",
  "Follow": "Підписатися", "Following": "Ви підписані", "Unfollow": "Відписатися", "Followers %lld": "Підписників: %lld",
  "Following %lld": "Підписок: %lld", "Buy coins": "Купити монети", "coins": "монет", "Coins purchased": "Баланс поповнено",
  "Step %lld of %lld": "Крок %lld з %lld", "Day %lld of %lld": "День %lld з %lld", "Week %lld": "Тиждень %lld",
  "today": "сьогодні", "yesterday": "вчора", "tomorrow": "завтра", "Ready!": "Готово!", "Start today": "Почати сьогодні",
  "Start tomorrow": "Почати завтра", "Start solo!": "Почати самостійно!", "Closed": "Закрито", "Missed": "Пропущено",
  "Upcoming": "Попереду", "Out": "Вибув", "Failed": "Провалено", "Private": "Приватний", "Public": "Публічний",
  "Solo": "Самостійно", "Just you": "Тільки ви", "Invite by link": "Запрошення за посиланням", "Anyone joins": "Може приєднатися кожен",
  "No": "Ні", "Yes": "Так", "None": "Немає", "Off": "Вимк.", "Other": "Інше", "Days": "Днів", "d": "д",
  "Easier": "Легше", "Recommended": "Рекомендовано", "Harder": "Складніше", "Popular challenges": "Популярні челенджі",
  "Open challenges": "Відкриті челенджі", "See all": "Переглянути всі", "How it works": "Як це працює",
  "Choose a goal": "Оберіть ціль", "Train with camera": "Тренуйтеся з камерою", "Keep your streak": "Підтримуйте серію",
  "No activity yet — be the first to train today.": "Активності ще немає — тренуйтеся сьогодні першими.",
  "Challenge a friend": "Киньте виклик другові", "Create a shared goal and send one link.": "Створіть спільну ціль і надішліть одне посилання."
};
