// Українська локалізація Repact. Внутрішній код мови — `ua`, формат дат — `uk-UA`.
window.UA_TRANSLATIONS = {
  "Choose language": "Оберіть мову",
  "How Repact works": "Як працює Repact", "Workouts you have to prove": "Тренування, які потрібно довести",
  "Repact counts your reps with the camera and verifies every result.": "Repact рахує повтори камерою та підтверджує кожен результат.",
  "Do the exercise": "Виконай вправу", "Get a verified result": "Отримай підтверджений результат",
  "The camera is your counter": "Камера — твій лічильник", "The app will tell you when to step back or add light.": "Застосунок підкаже, коли потрібно відійти далі або додати світла.",
  "Set the phone down and step back until your whole body is visible.": "Постав телефон і відійди так, щоб усе тіло було видно.",
  "Sound cues": "Звукові підказки", "Processed on your device": "Обробка на пристрої",
  "Choose how to start": "Обери, як почати", "Start with the path that fits you. You can try everything later.": "Почни з варіанта, який тобі підходить. Решту можна спробувати пізніше.",
  "Join a challenge": "Приєднатися до челенджу", "Pick a ready-made goal and start training.": "Обери готову ціль і почни тренування.",
  "Create your own": "Створити свій челендж", "Choose exercises, rules and invite friends.": "Обери вправи, правила та запроси друзів.",
  "Accept a friend's invite": "Прийняти запрошення друга", "Your invitation is saved.": "Твоє запрошення збережено.", "Open a link sent by a friend.": "Відкрий посилання, яке надіслав друг.",
  "Your testing checklist": "Твій чек-лист тестування", "You don't have to finish everything at once. Your progress is saved.": "Не обов’язково робити все одразу. Прогрес збережеться.",
  "Test the camera": "Протестувати камеру", "Join or create a challenge": "Приєднатися або створити челендж", "Invite a friend": "Запросити друга",
  "Complete a workout": "Виконати тренування", "Close your daily goal": "Закрити денну ціль", "Share your result": "Поділитися результатом", "View your progress": "Переглянути прогрес",
  "Found a problem?": "Знайшли проблему?", "Send a report from any screen.": "Надішліть звіт із будь-якого екрана.", "View invitation": "Переглянути запрошення", "Go to the app": "Перейти в застосунок",
  "Don't just say it.": "Не просто кажи.", "Prove it.": "Доведи це!", "Test Repact": "Тест Repact", "Skip": "Пропустити",
  "Home": "Головна", "Challenges": "Челенджі", "Progress": "Прогрес", "Profile": "Профіль",
  "Active": "Активні", "Pending": "Очікують", "Browse": "Огляд", "Completed": "Завершені",
  "Today": "Сьогодні", "Today in Repact": "Сьогодні в Repact", "All-time": "За весь час",
  "All-time reps": "Повторів за весь час", "Earlier reps": "Попередні повтори", "Total reps": "Усього повторів",
  "Statistics": "Статистика", "Stats": "Статистика", "Daily activity — 30 days": "Денна активність за 30 днів",
  "Challenge": "Челендж", "Challenge complete!": "Челендж завершено!", "Challenge failed": "Челендж провалено",
  "Create challenge": "Створити челендж", "Create Challenge": "Створити челендж", "New challenge": "Новий челендж",
  "Find a challenge": "Знайти челендж", "Start challenge": "Почати челендж", "Public challenge": "Публічний челендж",
  "Private challenge": "Приватний челендж", "Review challenge": "Перевірте челендж", "Challenge type": "Тип челенджу",
  "Active challenges: %lld": "Активних челенджів: %lld", "Challenges joined": "Участь у челенджах",
  "No active challenges": "Немає активних челенджів", "No public challenges yet": "Публічних челенджів поки немає",
  "Public challenges you can join show up here.": "Тут з’являться публічні челенджі, до яких можна приєднатися.",
  "No finished challenges yet": "Завершених челенджів поки немає", "Completed challenges will show up here.": "Тут з’являться завершені челенджі.",
  "Nothing pending": "Нічого не очікує", "Create a new challenge to get started!": "Створіть челендж, щоб почати!",
  "Continue workout": "Продовжити тренування", "Start today's workout": "Почати тренування на сьогодні",
  "Finish workout": "Завершити тренування", "Finish workout?": "Завершити тренування?", "Save workout": "Зберегти тренування",
  "Lower down": "Опустися нижче", "Push up": "Піднімися вище",
  "Workout saved": "Тренування збережено", "Workout sounds": "Звуки тренування", "Finish set": "Завершити підхід",
  "Start next set": "Почати наступний підхід", "Extra set": "Ще один підхід", "Rest": "Відпочинок",
  "Rest finished": "Відпочинок завершено", "Overall time": "Загальний час", "Day complete": "День завершено",
  "Day done!": "День завершено!", "Done": "Готово", "Done today": "Виконано сьогодні",
  "Done today: %lld/%lld": "Сьогодні: %lld/%lld", "Daily goal": "Денна ціль", "Goal reached!": "Цілі досягнуто!",
  "Push-ups": "Віджимання", "Squats": "Присідання", "Pull-ups": "Підтягування", "Dips": "Віджимання на брусах",
  "Push-ups per day": "Віджимань на день", "Squats per day": "Присідань на день", "Reps": "Повтори",
  "Reps per day": "Повторів на день", "reps per day": "повторів на день", "%lld reps": "%lld повторів",
  "%lld reps/day": "%lld повторів на день", "%lld / day": "%lld / день", "%lld days": "%lld днів",
  "%lld sets": "%lld підходів", "Sets": "Підходи", "Best set": "Найкращий підхід", "Average set": "Середній підхід",
  "Max reps": "Максимум за підхід", "Max reps in one set": "Максимум за підхід", "Time": "Час",
  "Try a demo workout": "Спробувати демо-тренування", "Choose an exercise": "Оберіть вправу",
  "Pick what you want to try. You can change it later.": "Оберіть, що хочете спробувати. Потім вибір можна змінити.",
  "AI Workout": "AI-тренування", "Try 5 reps": "Спробувати 5 повторів",
  "Get started": "Почати", "Let's go": "Уперед", "Continue": "Далі", "Back": "Назад", "Close": "Закрити",
  "Create": "Створити", "Save": "Зберегти", "Cancel": "Скасувати", "Finish": "Завершити", "Retry": "Спробувати ще",
  "Camera setup": "Налаштування камери", "Open camera": "Відкрити камеру", "Switch camera": "Змінити камеру",
  "Camera tracking": "Відстеження камерою", "Point the camera at yourself": "Наведіть камеру на себе",
  "Set your phone down": "Надійно встановіть телефон", "Fit your whole body in frame": "Розмістіть усе тіло в кадрі",
  "Use good lighting": "Додайте світла", "Step into frame": "Станьте в кадр", "Step back from the camera": "Відійдіть далі від камери",
  "Show both arms": "Покажіть обидві руки", "Show both legs": "Покажіть обидві ноги", "Position found": "Позицію знайдено",
  "Too dark — add more light": "Надто темно — додайте світла", "Body found — hold still": "Тіло знайдено — не рухайтесь",
  "Ready — start moving": "Готово — починайте рух", "Reconnecting camera…": "Перепідключаємо камеру…",
  "Lower your chest": "Опустіть груди нижче", "Squat lower": "Присядьте нижче", "Pull yourself higher": "Підтягніться вище",
  "Lower your body": "Опустіться нижче", "Go a little deeper": "Ще трохи нижче", "Go!": "Уперед!",
  "Camera check complete": "Перевірку камери завершено", "Try again": "Спробувати ще раз", "Not now": "Не зараз",
  "Camera permission denied": "Доступ до камери заборонено", "Camera not found": "Камеру не знайдено",
  "Internet connection required": "Потрібне підключення до інтернету", "Open Settings": "Відкрити налаштування",
  "Before": "До", "After": "Після", "Before / After": "До / Після", "Before / After photos": "Фото до / після",
  "Take a photo": "Зробити фото", "Take photo": "Зняти фото", "Upload": "Завантажити", "Upload from library": "Завантажити з галереї",
  "Photo library": "Фотогалерея", "Retake": "Перезняти", "Show photos": "Показати фото",
  "Share": "Поділитися", "Share result": "Поділитися результатом", "Share your day": "Поділитися днем",
  "Share story": "Поділитися сторіс", "Share today's result": "Поділитися результатом", "Save to profile": "Зберегти в профіль",
  "Choose a background": "Оберіть фон", "Template": "Шаблон", "Minimal": "Мінімал", "Repact gradient": "Градієнт Repact",
  "Rules": "Правила", "Conditions": "Умови", "Duration": "Тривалість", "Duration (days)": "Тривалість (днів)",
  "Exercise": "Вправа", "Which exercises?": "Які вправи?", "How many per day?": "Скільки на день?",
  "Daily goal for each exercise.": "Денна ціль для кожної вправи.", "Pick at least one exercise": "Оберіть хоча б одну вправу",
  "Name your challenge": "Назвіть челендж", "Challenge name": "Назва челенджу", "Title": "Назва",
  "Buy-in": "Внесок", "Stake amount": "Розмір ставки", "Prize pool": "Призовий фонд", "Balance": "Баланс",
  "Test coins · no cash value": "Тестові монети · без грошової вартості", "Test currency — no real money.": "Тестова валюта — без реальних грошей.",
  "Leaderboard": "Таблиця лідерів", "Members: %lld": "Учасників: %lld", "Eliminated: %lld": "Вибуло: %lld",
  "Join for": "Приєднатися за", "Leave challenge": "Вийти з челенджу", "Leave challenge?": "Вийти з челенджу?",
  "Leave": "Вийти", "Keep going": "Продовжити", "Invite friends": "Запросити друзів", "Link copied": "Посилання скопійовано",
  "Your name": "Ваше ім’я", "Age": "Вік", "Gender": "Стать", "Male": "Чоловіча", "Female": "Жіноча",
  "Height": "Зріст", "Weight": "Вага", "Fitness level": "Рівень підготовки", "Beginner": "Початківець",
  "Athlete": "Атлет", "Measurements": "Заміри", "New measurement": "Новий замір", "kg": "кг", "cm": "см",
  "Account": "Акаунт", "Email": "Електронна пошта", "Password": "Пароль", "Log in": "Увійти", "Log out": "Вийти",
  "Sign up": "Зареєструватися", "Create account": "Створити акаунт", "Create your account": "Створіть акаунт",
  "Continue with Google": "Продовжити з Google", "Continue with Facebook": "Продовжити з Facebook", "Continue as guest": "Продовжити як гість", "Guest": "Гість", "or": "або",
  "Notifications": "Сповіщення", "No notifications yet": "Сповіщень поки немає", "Report a problem": "Повідомити про проблему",
  "Send report": "Надіслати", "Thanks! Report sent.": "Дякуємо! Звіт надіслано.",
  "Counting & camera": "Підрахунок і камера", "Design & layout": "Дизайн і верстка", "App behavior": "Робота застосунку",
  "Follow": "Підписатися", "Following": "Ви підписані", "Unfollow": "Відписатися", "Followers %lld": "Підписників: %lld",
  "Following %lld": "Підписок: %lld", "Buy coins": "Купити монети", "coins": "монет", "Coins purchased": "Баланс поповнено",
  "Step %lld of %lld": "Крок %lld з %lld", "Day %lld of %lld": "День %lld з %lld", "Week %lld": "Тиждень %lld",
  "today": "сьогодні", "yesterday": "вчора", "tomorrow": "завтра", "Ready!": "Готово!", "Start today": "Почати сьогодні",
  "Start tomorrow": "Почати завтра", "Start solo!": "Почати самостійно!", "Closed": "Закрито", "Missed": "Пропущено",
  "Upcoming": "Попереду", "Out": "Вибув", "Failed": "Провалено", "Private": "Приватний", "Public": "Публічний",
  "Solo": "Самостійно", "Just you": "Тільки ви", "Invite by link": "Запрошення за посиланням", "Anyone joins": "Може приєднатися кожен",
  "No": "Ні", "Yes": "Так", "None": "Немає", "Off": "Вимк.", "Other": "Інше", "Days": "Днів", "d": "д",
  "Easier": "Легше", "Recommended": "Рекомендовано", "Harder": "Складніше", "Popular challenges": "Популярні челенджі",
  "Open challenges": "Відкриті челенджі", "See all": "Переглянути всі", "How it works": "Як це працює",
  "Choose a goal": "Оберіть ціль", "Train with camera": "Тренуйтеся з камерою", "Keep your streak": "Підтримуйте серію",
  "No activity yet — be the first to train today.": "Активності ще немає — тренуйтеся сьогодні першими.",
  "Challenge a friend": "Киньте виклик другові", "Create a shared goal and send one link.": "Створіть спільну ціль і надішліть одне посилання."
};

Object.assign(window.UA_TRANSLATIONS, {
  "Shared!": "Готово!", "Your result has been shared.": "Результатом поділилися.",
  "Back to result": "Повернутися до результату", "Go to Home": "На головну",
  "Coins": "Монети", "Test coins for joining challenges. They have no cash value.": "Тестові монети для участі в челенджах. Вони не мають грошової цінності.",
  "Restore test balance": "Відновити тестовий баланс", "Test balance restored": "Тестовий баланс відновлено",
  "%lld cm": "%lld см", "%lld days — finished": "%lld днів — завершено",
  "%lld in one set × %lld sets": "%lld за підхід × %lld підходів", "%lld kg": "%lld кг",
  "%lld of %lld already did it today": "%lld з %lld вже виконали сьогодні",
  "%lld reps today. Day %lld of %lld in the bag.": "%lld повторів сьогодні. День %lld з %lld завершено.",
  "%lld years": "%lld років", "+%lld more": "ще %lld", "1 per 2 weeks": "1 раз на 2 тижні",
  "1 per challenge": "1 раз за челендж", "A few times a week": "Кілька разів на тиждень",
  "Almost every day": "Майже щодня", "Before you start": "Перед початком",
  "Both arms must be fully in frame": "Обидві руки мають повністю бути в кадрі",
  "Both legs must be fully in frame": "Обидві ноги мають повністю бути в кадрі",
  "Buy-in: %@": "Внесок: %@", "Buy-in: %lld. Drop out — it stays in the pot for the finishers.": "Внесок: %lld. Якщо вибуваєте, він залишається в банку для фінішерів.",
  "Camera access is needed for the photo.": "Для фото потрібен доступ до камери.",
  "Camera access is needed to count your reps.": "Для підрахунку повторів потрібен доступ до камери.",
  "Ultra-wide 0.5×": "Надширококутна 0,5×", "Your camera counts every rep and helps you keep honest form.": "Камера рахує кожен повтор і допомагає дотримуватися правильної техніки.",
  "Story": "Сторіс", "Fill the frame": "Заповніть кадр", "Prove it": "Доведіть", "No equipment": "Без обладнання",
  "Quick challenge": "Швидкий челендж", "Tips & quick start": "Підказки та швидкий старт", "Hide tips": "Сховати підказки",
  "7-day Push-up Challenge": "7-денний челендж із віджимань",
  "7 days · 20 push-ups a day": "7 днів · 20 віджимань на день",
  "Keep the camera still so every rep can be verified.": "Зафіксуйте камеру, щоб кожен повтор можна було перевірити.",
  "Step back until your arms and legs are clearly visible.": "Відійдіть так, щоб руки й ноги було чітко видно.",
  "Face the light and avoid a bright window behind you.": "Станьте обличчям до світла й уникайте яскравого вікна позаду.",
  "Your video stays on this device and is not uploaded.": "Відео залишається на цьому пристрої та нікуди не завантажується.",
  "Demo complete — join a challenge to save progress.": "Демо завершено — приєднайтеся до челенджу, щоб зберігати прогрес.",
  "Good depth — straighten fully": "Гарна глибина — повністю випряміться",
  "Your reps were recognized correctly. Join a challenge to start saving progress.": "Повтори розпізнано правильно. Приєднайтеся до челенджу, щоб зберігати прогрес.",
  "You’ll get 50 test coins. Guest progress stays only on this device.": "Ви отримаєте 50 тестових монет. Прогрес гостя зберігається лише на цьому пристрої.",
  "Progress is stored only on this device": "Прогрес зберігається лише на цьому пристрої",
  "Create an account to sync progress and use social challenges.": "Створіть акаунт, щоб синхронізувати прогрес і брати участь у спільних челенджах.",
  "Account required": "Потрібен акаунт",
  "To join this challenge, create an account so your progress is saved and visible to other participants.": "Щоб приєднатися, створіть акаунт — прогрес збережеться та буде видимий іншим учасникам.",
  "To publish or share a challenge, create an account so participants and progress can sync.": "Щоб опублікувати або поширити челендж, створіть акаунт для синхронізації учасників і прогресу.",
  "Your private challenge works on this device without an account.": "Приватний челендж працює на цьому пристрої без акаунта.",
  "Maybe later": "Можливо, пізніше", "Customize preset": "Налаштувати шаблон", "1 month": "1 місяць", "2 months": "2 місяці",
  "Private on this device": "Приватний · на цьому пристрої", "20 Dips Daily": "20 віджимань на брусах щодня",
  "30 days · 20 a day": "30 днів · 20 на день", "Preparing workout…": "Готуємо тренування…",
  "Interface sounds": "Звуки інтерфейсу", "%@ completed": "%@ — виконано", "Recording started": "Запис розпочато",
  "Set %lld completed": "Підхід %lld завершено", "Total %@": "Усього %@", "+30 sec": "+30 с",
  "avg %lld": "у середньому %lld", "%lld sec faster": "на %lld с швидше", "Save completed reps?": "Зберегти виконані повтори?",
  "Exit without saving": "Вийти без збереження", "Couldn't save. Try again.": "Не вдалося зберегти. Спробуйте ще раз.",
  "Allow camera access in your browser settings, then retry.": "Дозвольте доступ до камери в налаштуваннях браузера й повторіть спробу.",
  "Couldn't load pose recognition": "Не вдалося завантажити розпізнавання пози", "Challenge total": "Усього за челендж",
  "Voice guidance": "Голосові підказки", "Record video": "Записувати відео", "Combo": "Комбо", "Currency": "Валюта",
  "Pick one or several — a combo counts them all.": "Оберіть одну або кілька — комбо рахує всі.",
  "Save & share": "Зберегти й поділитися", "Progression": "Прогресія", "%lld-day challenge": "Челендж на %lld днів",
  "Next exercise": "Наступна вправа", "Where to start?": "З чого почати?",
  "Day 1: %lld → Day %lld: %lld": "День 1: %lld → День %lld: %lld", "Do today's combo": "Виконати сьогоднішнє комбо",
  "Do today's push-ups": "Виконати сьогоднішні віджимання", "Do today's squats": "Виконати сьогоднішні присідання",
  "Each bar is one day.": "Кожен стовпчик — один день.", "Every": "Кожні", "Every day: ": "Щодня: ",
  "Every rep is verified by the camera in real time.": "Кожен повтор перевіряється камерою в реальному часі.",
  "Every rep is verified by the camera. Coins on the line. Miss too many days and you're out.": "Кожен повтор перевіряє камера. Монети на кону. Забагато пропусків — і ви вибуваєте.",
  "Exercise journal": "Журнал вправ", "Extra reps": "Додаткові повтори", "Finish: day %lld": "Фініш: день %lld",
  "Finished: %lld": "Завершено: %lld", "How many push-ups can you do in one set?": "Скільки віджимань ви можете зробити за один підхід?",
  "I barely train": "Майже не тренуюся", "Increase by: %lld reps": "Збільшення: %lld повторів",
  "Challenge restarted — keep going!": "Челендж перезапущено — продовжуйте!",
  "Your buy-in won't be refunded and you won't be able to see the results.": "Внесок не повернеться, і ви більше не зможете переглядати результати.",
  "Max reps in one set: %lld": "Максимум за підхід: %lld", "Missed days": "Пропущені дні",
  "No measurements yet. They're added after each challenge.": "Замірів поки немає. Вони додаються після кожного челенджу.",
  "No missed days: skip one and you're out. The pot is split between everyone who finishes.": "Пропуски не дозволені: пропустили день — вибули. Банк ділиться між усіма, хто фінішував.",
  "Not enough coins": "Недостатньо монет", "Opens at the finish": "Відкриється на фініші", "per day": "на день", "per week": "на тиждень",
  "Photo BEFORE": "Фото ДО", "Photos appear here once you join a challenge with a BEFORE photo.": "Фото з’являться тут після приєднання до челенджу з фото ДО.",
  "Practice": "Тренування", "Progressive overload": "Прогресивне навантаження", "Regular": "Тренуюся регулярно",
  "Reps can be split into any number of sets during the day.": "Повтори можна розділити на будь-яку кількість підходів протягом дня.",
  "Schedule": "Розклад", "Show result": "Показати результат", "Starting balance": "Початковий баланс",
  "The buy-in is deducted from your balance right away. Test currency — no real money.": "Внесок одразу списується з балансу. Валюта тестова — без реальних грошей.",
  "The challenge runs %lld days.": "Челендж триває %lld днів.", "The daily goal grows as the challenge goes on.": "Денна ціль зростає протягом челенджу.",
  "The goal grows by %lld reps every day — by day %lld it's %lld.": "Ціль зростає на %lld повторів щодня — на день %lld вона становитиме %lld.",
  "The goal grows by %lld reps every week — by day %lld it's %lld.": "Ціль зростає на %lld повторів щотижня — на день %lld вона становитиме %lld.",
  "The photo stays hidden until the finish — then it appears next to your AFTER photo.": "Фото приховане до фінішу — тоді воно з’явиться поруч із фото ПІСЛЯ.",
  "Total reps over the last 4 weeks.": "Усього повторів за останні 4 тижні.", "Photo scale": "Масштаб фото",
  "Background dimming": "Затемнення фону", "Drag the photo to position it": "Перетягніть фото, щоб змінити його положення"
});

Object.assign(window.UA_TRANSLATIONS, {
  "Authentication service is still loading — try again": "Сервіс входу ще завантажується — спробуйте ще раз",
  "Email registration is temporarily unavailable. Try Google.": "Реєстрація через пошту тимчасово недоступна. Спробуйте Google.",
  "Open the app at http://localhost:8000 to sign in": "Відкрийте застосунок через http://localhost:8000, щоб увійти",
  "30-day Push-up Challenge": "30-денний челендж із віджимань", "50 push-ups a day for a month": "50 віджимань на день протягом місяця",
  "100 Squats Daily": "100 присідань щодня", "30 days · 100 a day": "30 днів · 100 на день",
  "Pull-up Progression": "Прогресія підтягувань", "Grows a bit every week": "Потроху зростає щотижня",
  "So your progress is saved and syncs across your devices": "Щоб прогрес зберігався та синхронізувався між пристроями",
  "Allow popups and try again": "Дозвольте спливні вікна й спробуйте ще раз",
  "Enable Google in Firebase (Sign-in method)": "Увімкніть Google у Firebase (спосіб входу)",
  "Enable Facebook in Firebase (Sign-in method)": "Увімкніть Facebook у Firebase (спосіб входу)",
  "Add domain in Firebase (Authorized domains)": "Додайте домен у Firebase (дозволені домени)",
  "Google sign-in unavailable here — use email": "Вхід через Google тут недоступний — використайте пошту",
  "Add to Home Screen: Share → Add to Home Screen": "На головний екран: Поділитися → На початковий екран",
  "Describe the bug: what happened and how to repeat it…": "Опиши баг: що сталося і як це повторити…",
  "What broke": "Що зламалося", "How bad": "Наскільки серйозно",
  "Low": "Дрібниця", "Normal": "Звичайний", "High": "Важливий", "Critical": "Критично",
  "Attach a screenshot": "Прикріпити скріншот", "Remove screenshot": "Прибрати скріншот",
  "Screen, size and browser are attached automatically.": "Екран, розмір і браузер додаються автоматично.",
  "Couldn't send — check connection": "Не вдалося надіслати — перевірте з’єднання", "Challenges & money": "Челенджі та монети",
  "+%lld coins": "+%lld монет", "Daily minimum reps": "Мінімум повторів на день", "Goal": "Ціль",
  "Hit a total rep target": "Набрати загальну кількість повторів", "Custom": "Своє", "Who can join": "Хто може приєднатися",
  "Players to gather": "Скільки гравців зібрати", "Stake & rules": "Ставка та правила",
  "Private and public challenges waiting to start show up here.": "Тут з’являться приватні та публічні челенджі, які очікують старту.",
  "%@ completed %@ in %@": "%@ виконав вправу «%@» у «%@»", "%@ completed today's challenge in %@": "%@ виконав сьогоднішню ціль у «%@»",
  "just now": "щойно", "%lld min ago": "%lld хв тому", "%lld h ago": "%lld год тому",
  "Couldn't update subscription": "Не вдалося оновити підписку"
});

Object.assign(window.UA_TRANSLATIONS, {
  "Couldn't publish challenge": "Не вдалося опублікувати челендж",
  "Couldn't leave challenge": "Не вдалося вийти з челенджу", "Couldn't join challenge": "Не вдалося приєднатися до челенджу", "Joining…": "Приєднуємося…",
  "Creator": "Автор", "Joined": "Приєднався", "Loading public challenges…": "Завантажуємо публічні челенджі…",
  "Couldn't load public challenges. Check connection.": "Не вдалося завантажити публічні челенджі. Перевірте з’єднання.",
  "In progress": "Триває", "So your progress is saved and syncs across your devices.": "Щоб прогрес зберігався та синхронізувався між пристроями.",
  "Challenge created": "Челендж створено", "Invite people now or share it later from the challenge page.": "Запросіть людей зараз або поділіться пізніше зі сторінки челенджу.",
  "Share invite": "Поділитися запрошенням", "Copy link": "Скопіювати посилання", "Open challenge": "Відкрити челендж",
  "Join my challenge": "Приєднуйся до мого челенджу"
});

Object.assign(window.UA_TRANSLATIONS, {
  "I did mine": "Я своє зробив", "Now it's your turn": "Тепер ваша черга", "Potential reward": "Можлива винагорода",
  "Above goal": "Понад ціль", "Best day": "Найкращий день", "Today's place": "Місце сьогодні", "Streak": "Серія",
  "This week": "Цього тижня", "Last 30 days": "Останні 30 днів", "Active days": "Активні дні",
  "Best streak": "Найкраща серія", "Current streak": "Поточна серія", "Personal records": "Особисті рекорди",
  "Recent workouts": "Останні тренування", "Daily best": "Рекорд дня", "No reps yet": "Повторів поки немає",
  "Show all workouts": "Показати всі тренування", "Collapse workouts": "Згорнути тренування",
  "Push-ups short": "Віджимання", "Squats short": "Присідання", "Pull-ups short": "Підтягування", "Dips short": "Бруси",
  "Reps · 30 days": "Повтори · 30 днів", "Completion": "Виконання", "All": "Усі", "%lld of %lld": "%lld з %lld",
  "reps": "повторів", "Exercises": "Вправи", "AI verified": "Перевірено AI", "Avg / set": "Середнє / підхід",
  "Day": "День", "faster than last time": "швидше, ніж минулого разу", "Body & measurements": "Тіло та заміри",
  "Wallet": "Гаманець", "Privacy & data": "Приватність і дані",
  "Video is processed on your device by the camera — not recorded and not sent to any server.": "Відео обробляється камерою на вашому пристрої — не записується й не надсилається на сервер.",
  "Before / After photos are stored on your device — the app doesn't upload them to our servers.": "Фото до / після зберігаються на вашому пристрої — застосунок не завантажує їх на наші сервери.",
  "Privacy Policy": "Політика конфіденційності", "Delete account and data": "Видалити акаунт і дані",
  "Weight and measurements stay on this device.": "Вага та заміри залишаються на цьому пристрої.",
  "Nothing is used to train any models.": "Жодні дані не використовуються для навчання моделей.",
  "Weekly volume": "Тижневий обсяг", "Weight: %lld kg": "Вага: %lld кг", "Yesterday %lld dropped out": "Учора вибуло: %lld",
  "You": "Ви", "You can miss 1 day during the whole challenge, more and you're out. The pot is split between everyone who finishes.": "Можна пропустити 1 день за весь челендж. Більше — і ви вибуваєте. Банк ділиться між усіма, хто фінішував.",
  "You can miss 1 day every 2 weeks, more and you're out. The pot is split between everyone who finishes.": "Можна пропускати 1 день кожні 2 тижні. Більше — і ви вибуваєте. Банк ділиться між усіма, хто фінішував.",
  "You take home": "Ви отримуєте", "You'd win": "Ваш виграш",
  "You're not in any challenge yet. Join one and put some coins on the line.": "Ви ще не берете участі в челенджах. Приєднайтеся та поставте монети на кон.",
  "Your age": "Ваш вік", "Your Challenges": "Ваші челенджі", "Your daily goal": "Ваша денна ціль",
  "Your data": "Ваші дані", "Your fitness level": "Ваш рівень підготовки", "Your gender": "Ваша стать",
  "Your height": "Ваш зріст", "Your physical profile": "Ваші фізичні дані", "yrs": "років",
  "Your exercises": "Ваші вправи", "Pick what you train and set your one-set max.": "Оберіть вправи та вкажіть максимум за один підхід.",
  "Pick what you train. Repact will measure your progress from verified workouts.": "Оберіть, що тренуєте. Repact сам виміряє прогрес за підтвердженими тренуваннями.",
  "Strength progress": "Прогрес сили", "Verified sets only": "Лише підтверджені сети",
  "First workout": "Перше тренування", "Best set": "Найкращий сет", "Latest workout": "Останнє тренування",
  "%@ level → %lld working sets per exercise.": "Рівень %@ → %lld робочих підходів на вправу.",
  "This information is used to personalize your first week workout program. You can edit it later from your profile page.": "Ці дані потрібні для персоналізації першого тижня тренувань. Їх можна змінити пізніше в профілі.",
  "Your starting point — at the finish you'll see how far you've come.": "Ваша стартова точка — на фініші побачите свій прогрес.",
  "Your weight": "Ваша вага", "Your whole body must be in frame": "Усе тіло має бути в кадрі", "Yours": "Ваші",
  "Language": "Мова", "Edit": "Редагувати", "Increase by": "Збільшувати на", "Settings": "Налаштування",
  "Choose a workout": "Оберіть тренування", "Pick what you want to complete today.": "Оберіть, що хочете виконати сьогодні.",
  "Friends feed": "Стрічка друзів", "When friends complete their day — it shows up here.": "Коли друзі виконують денну ціль, це з’являється тут.",
  "All done for today": "На сьогодні все виконано", "%lld left": "залишилося %lld", "%lldh %lldm": "%lld год %lld хв",
  "Insights": "Висновки", "This week +%lld% more reps": "Цього тижня на %lld% більше повторів",
  "This week %lld% fewer reps": "Цього тижня на %lld% менше повторів", "On track %lld days in a row": "Ціль виконано %lld днів поспіль",
  "%lld reps to your daily record": "До денного рекорду залишилося %lld повторів", "Most active day — %@": "Найактивніший день — %@",
  "Complete your first workout and your weekly trend will appear here.": "Завершіть перше тренування — тут з’явиться тижнева динаміка.",
  "Friends will see it in the leaderboard.": "Друзі побачать це в таблиці лідерів.",
  "Join my challenge — 150 push-ups + 50 squats a day!": "Приєднуйся до мого челенджу — 150 віджимань і 50 присідань на день!",
  "In the app: %lld": "У застосунку: %lld", "%lld players": "Гравців: %lld",
  "Gathered %lld / %lld · %lld ready": "Зібрано %lld / %lld · готові %lld",
  "Waiting for everyone to gather and get ready…": "Чекаємо, поки всі зберуться та будуть готові…",
  "Waiting for the creator to start…": "Чекаємо, поки автор запустить челендж…",
  "Couldn't start challenge": "Не вдалося запустити челендж", "Couldn't mark ready": "Не вдалося позначити готовність",
  "“%@” starts %@": "«%@» починається %@", "Do today's pull-ups": "Виконати сьогоднішні підтягування",
  "Do today's dips": "Виконати сьогоднішні віджимання на брусах", "You didn't finish this one.": "Цього разу ви не дійшли до фінішу.",
  "Finishers": "Фінішери", "A new season starts soon.": "Новий сезон скоро почнеться.", "Day streak": "Днів поспіль",
  "%lld-day streak": "%lld днів поспіль", "You missed more days than the protection allows.": "Ви пропустили більше днів, ніж дозволяє захист.",
  "It will move to Completed in a couple of days.": "За кілька днів челендж перейде до завершених.",
  "Signed in": "Вхід виконано", "Signing in…": "Вхід…", "Skip for now": "Поки пропустити",
  "Sign in to sync progress across your devices": "Увійдіть, щоб синхронізувати прогрес між пристроями",
  "Synced across your devices": "Прогрес синхронізується між пристроями", "Enter email and password": "Введіть електронну пошту та пароль",
  "Wrong password": "Неправильний пароль", "Password too short (min 6)": "Пароль надто короткий (мінімум 6 символів)",
  "Invalid email": "Некоректна електронна пошта", "Network error": "Помилка мережі", "Couldn't sign in": "Не вдалося увійти",
  "Email already registered — log in": "Ця пошта вже зареєстрована — увійдіть", "No account yet — sign up": "Ще немає акаунта — зареєструйтеся",
  "Which exercise do you want to start with?": "З якої вправи хочете почати?", "%lld in Repact": "%lld у Repact",
  "Create from scratch": "Створити з нуля", "Tap any card to make changes before creating.": "Натисніть картку, щоб змінити її перед створенням.",
  "Exercise & daily goal": "Вправи та денна ціль", "Pick exercises and set a goal for each.": "Оберіть вправи та встановіть ціль для кожної.",
  "How long?": "Яка тривалість?", "Choose how long the challenge will run.": "Оберіть тривалість челенджу.",
  "2 weeks": "2 тижні", "Good for a quick start": "Добре для швидкого старту", "Balanced challenge": "Збалансований челендж",
  "Long-term progress": "Довгостроковий прогрес", "Custom duration": "Своя тривалість", "Rules & stake": "Правила та ставка",
  "Set the final details before review.": "Налаштуйте останні деталі перед перевіркою.", "Save changes": "Зберегти зміни",
  "Missed days decide how many unfinished days you can have before you leave the challenge and lose your stake.": "Пропущені дні визначають, скільки разів можна не виконати денну ціль, перш ніж ви залишите челендж і втратите ставку.",
  "No protection": "Без захисту", "Miss one day and you're out.": "Один пропуск — і ви вибуваєте.",
  "One safety day": "Один запасний день", "You can miss once during the whole challenge.": "Можна один раз пропустити за весь челендж.",
  "Recurring protection": "Регулярний захист", "You can miss once in every 14 days.": "Можна пропускати один раз кожні 14 днів.",
  "Increase your daily target gradually as you get stronger.": "Поступово збільшуйте денну ціль, коли стаєте сильнішими.",
  "Final daily target": "Ціль в останній день", "No increase — the daily target stays the same.": "Без збільшення — денна ціль залишиться незмінною.",
  "Publishing challenge…": "Публікуємо челендж…",
  "Couldn't publish challenge. Check your connection and try again.": "Не вдалося опублікувати челендж. Перевірте з’єднання та спробуйте ще раз.",
  "Review": "Перевірка", "Step %lld of 3": "Крок %lld з 3", "Goal": "Ціль", "What are you proving?": "Що ти доводиш?",
  "Choose a challenge type, exercises and the target.": "Обери тип челенджу, вправи та ціль.",
  "Daily streak": "Щодня", "Complete the target every day": "Виконуй ціль кожного дня",
  "Total goal": "Загальна ціль", "Reach one total during the challenge": "Набери загальну кількість за челендж",
  "Exercises": "Вправи", "Format": "Формат", "How will it work?": "Як це працюватиме?",
  "Set duration and who can join.": "Обери тривалість і хто може приєднатися.", "Starts today · %lld days": "Старт сьогодні · %lld дн.",
  "By invitation": "За запрошенням", "Only people with your link": "Тільки люди з твоїм посиланням",
  "Anyone can join": "Може приєднатися кожен", "Only me": "Тільки я", "A personal challenge": "Особистий челендж",
  "Limit participants": "Обмежити учасників", "Unlimited participants": "Без обмежень", "Participants": "Учасники",
  "Up to %lld participants": "До %lld учасників", "Public · unlimited": "Публічний · без обмежень",
  "Public · up to %lld": "Публічний · до %lld", "Final conditions": "Фінальні умови",
  "Set misses, progression, stake and name.": "Налаштуй пропуски, навантаження, ставку та назву.",
  "Allowed misses": "Дозволені пропуски", "Stake": "Ставка", "Balance": "Баланс", "No stake": "Без ставки",
  "Check the conditions before publishing.": "Перевір умови перед публікацією.",
  "No daily rules": "Без щоденних правил", "total": "усього",
  "Complete all required fields": "Заповни обов’язкові поля", "Challenge is full": "У челенджі немає вільних місць",
  "Reset test data": "Скинути тестові дані", "Reset all test data?": "Скинути всі тестові дані?",
  "This removes your local profile, workouts, photos and test coins from this device. This cannot be undone.": "З пристрою буде видалено локальний профіль, тренування, фото й тестові монети. Цю дію не можна скасувати.",
  "Reset and start over": "Скинути й почати спочатку",
  "Camera frames are processed on this device and are not uploaded to our servers.": "Кадри камери обробляються на цьому пристрої та не завантажуються на наші сервери.",
  "Video is recorded only when you tap Record and stays on your device unless you choose to share it.": "Відео записується лише після натискання кнопки запису й залишається на пристрої, доки ви самі ним не поділитеся.",
  "We use PostHog and Firebase Analytics to understand product usage and improve the test app.": "Ми використовуємо PostHog і Firebase Analytics, щоб розуміти використання продукту та покращувати тестовий застосунок."
});
